### ISSUE TITLE
Issue With Initialization

### ISSUE THREAD

**Issue by mridenour7** [AlexisDusart/ISSumSet#2]
Hi Alexis, I've been running into a few issues with loading and preprocessing the dataset. The TREC IS website no longer distinguishes between test and train sets for 2018 and 2019, so I'm not sure if I downloaded the correct data. Also, it looks like some of the JSON formatting has changed, since `initialization.py` was giving me errors about the "allProperties" field not being found in the tweet files.

I really like the concept of this dataset and would like to be able to use it: do you happen to have a copy of the preprocessed/cleaned data that I could use in the meantime?

Thanks so much for this work!

**Comment by AlexisDusart** [comment]
Thanks for your interest in my work!
I took care of this issue in the last commit. It should be working now! :)

**Comment by mridenour7** [comment]
Thank you for the quick response, it's working now!
